# Generated by Django 2.2 on 2021-07-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_reboot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
