# Generated by Django 2.2 on 2021-07-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_reboot_app', '0002_article_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='saved',
            field=models.BooleanField(default=True),
        ),
    ]
