# Generated by Django 2.2 on 2021-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_reboot_app', '0003_auto_20210711_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
